// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dht.proto

package dht_pb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	pb "github.com/libp2p/go-libp2p-record/pb"
	pb1 "github.com/libp2p/go-libp2p/core/crypto/pb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Message_ConnectionType int32

const (
	// sender does not have a connection to peer, and no extra information (default)
	Message_NOT_CONNECTED Message_ConnectionType = 0
	// sender has a live connection to peer
	Message_CONNECTED Message_ConnectionType = 1
	// sender recently connected to peer
	Message_CAN_CONNECT Message_ConnectionType = 2
	// sender recently tried to connect to peer repeatedly but failed to connect
	// ("try" here is loose, but this should signal "made strong effort, failed")
	Message_CANNOT_CONNECT Message_ConnectionType = 3
)

var Message_ConnectionType_name = map[int32]string{
	0: "NOT_CONNECTED",
	1: "CONNECTED",
	2: "CAN_CONNECT",
	3: "CANNOT_CONNECT",
}

var Message_ConnectionType_value = map[string]int32{
	"NOT_CONNECTED":  0,
	"CONNECTED":      1,
	"CAN_CONNECT":    2,
	"CANNOT_CONNECT": 3,
}

func (x Message_ConnectionType) String() string {
	return proto.EnumName(Message_ConnectionType_name, int32(x))
}

func (Message_ConnectionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_616a434b24c97ff4, []int{0, 0}
}

type Message struct {
	// defines what type of message it is.
	Feature string `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	// Used to specify the key associated with this message.
	// PUT_VALUE, GET_VALUE, ADD_PROVIDER, GET_PROVIDERS
	Key []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Used to return a value
	// PUT_VALUE, GET_VALUE
	Record *pb.Record `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	// Used to return Providers
	// GET_VALUE, ADD_PROVIDER, GET_PROVIDERS
	ProviderPeers []Message_Peer `protobuf:"bytes,9,rep,name=providerPeers,proto3" json:"providerPeers"`
	// Used to return peers closer to a key in a query
	// GET_VALUE, GET_PROVIDERS, FIND_NODE
	CloserPeers []Message_Peer `protobuf:"bytes,8,rep,name=closerPeers,proto3" json:"closerPeers"`
	// defines what coral cluster level this query/response belongs to.
	// in case we want to implement coral's cluster rings in the future.
	ClusterLevelRaw      int32                 `protobuf:"varint,10,opt,name=clusterLevelRaw,proto3" json:"clusterLevelRaw,omitempty"`
	ProviderPeersII      []Message_PeerWithKey `protobuf:"bytes,11,rep,name=providerPeersII,proto3" json:"providerPeersII"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_616a434b24c97ff4, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetFeature() string {
	if m != nil {
		return m.Feature
	}
	return ""
}

func (m *Message) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Message) GetRecord() *pb.Record {
	if m != nil {
		return m.Record
	}
	return nil
}

func (m *Message) GetProviderPeers() []Message_Peer {
	if m != nil {
		return m.ProviderPeers
	}
	return nil
}

func (m *Message) GetCloserPeers() []Message_Peer {
	if m != nil {
		return m.CloserPeers
	}
	return nil
}

func (m *Message) GetClusterLevelRaw() int32 {
	if m != nil {
		return m.ClusterLevelRaw
	}
	return 0
}

func (m *Message) GetProviderPeersII() []Message_PeerWithKey {
	if m != nil {
		return m.ProviderPeersII
	}
	return nil
}

type Message_Peer struct {
	// ID of a given peer.
	Id byteString `protobuf:"bytes,1,opt,name=id,proto3,customtype=byteString" json:"id"`
	// multiaddrs for a given peer
	Addrs [][]byte `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	// used to signal the sender's connection capabilities to the peer
	Connection           Message_ConnectionType `protobuf:"varint,3,opt,name=connection,proto3,enum=dht.pb.Message_ConnectionType" json:"connection,omitempty"`
	Features             []string               `protobuf:"bytes,4,rep,name=features,proto3" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Message_Peer) Reset()         { *m = Message_Peer{} }
func (m *Message_Peer) String() string { return proto.CompactTextString(m) }
func (*Message_Peer) ProtoMessage()    {}
func (*Message_Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_616a434b24c97ff4, []int{0, 0}
}
func (m *Message_Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Peer.Unmarshal(m, b)
}
func (m *Message_Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Peer.Marshal(b, m, deterministic)
}
func (m *Message_Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Peer.Merge(m, src)
}
func (m *Message_Peer) XXX_Size() int {
	return xxx_messageInfo_Message_Peer.Size(m)
}
func (m *Message_Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Peer proto.InternalMessageInfo

func (m *Message_Peer) GetAddrs() [][]byte {
	if m != nil {
		return m.Addrs
	}
	return nil
}

func (m *Message_Peer) GetConnection() Message_ConnectionType {
	if m != nil {
		return m.Connection
	}
	return Message_NOT_CONNECTED
}

func (m *Message_Peer) GetFeatures() []string {
	if m != nil {
		return m.Features
	}
	return nil
}

type Message_PeerWithKey struct {
	// ID of a given peer.
	Id byteString `protobuf:"bytes,1,opt,name=id,proto3,customtype=byteString" json:"id"`
	// multiaddrs for a given peer
	Addrs [][]byte `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	// used to signal the sender's connection capabilities to the peer
	Connection Message_ConnectionType `protobuf:"varint,3,opt,name=connection,proto3,enum=dht.pb.Message_ConnectionType" json:"connection,omitempty"`
	// key provided by peer; only set for GET_PROVIDER prefix lookups
	Key []byte `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	// signature of the provided key + encrypted peer ID for ADD_PROVIDER messages
	Signature []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	// public key of the peer for ADD_PROVIDER messages
	PublicKey            *pb1.PublicKey `protobuf:"bytes,6,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Message_PeerWithKey) Reset()         { *m = Message_PeerWithKey{} }
func (m *Message_PeerWithKey) String() string { return proto.CompactTextString(m) }
func (*Message_PeerWithKey) ProtoMessage()    {}
func (*Message_PeerWithKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_616a434b24c97ff4, []int{0, 1}
}
func (m *Message_PeerWithKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_PeerWithKey.Unmarshal(m, b)
}
func (m *Message_PeerWithKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_PeerWithKey.Marshal(b, m, deterministic)
}
func (m *Message_PeerWithKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_PeerWithKey.Merge(m, src)
}
func (m *Message_PeerWithKey) XXX_Size() int {
	return xxx_messageInfo_Message_PeerWithKey.Size(m)
}
func (m *Message_PeerWithKey) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_PeerWithKey.DiscardUnknown(m)
}

var xxx_messageInfo_Message_PeerWithKey proto.InternalMessageInfo

func (m *Message_PeerWithKey) GetAddrs() [][]byte {
	if m != nil {
		return m.Addrs
	}
	return nil
}

func (m *Message_PeerWithKey) GetConnection() Message_ConnectionType {
	if m != nil {
		return m.Connection
	}
	return Message_NOT_CONNECTED
}

func (m *Message_PeerWithKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Message_PeerWithKey) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Message_PeerWithKey) GetPublicKey() *pb1.PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func init() {
	proto.RegisterEnum("dht.pb.Message_ConnectionType", Message_ConnectionType_name, Message_ConnectionType_value)
	proto.RegisterType((*Message)(nil), "dht.pb.Message")
	proto.RegisterType((*Message_Peer)(nil), "dht.pb.Message.Peer")
	proto.RegisterType((*Message_PeerWithKey)(nil), "dht.pb.Message.PeerWithKey")
}

func init() { proto.RegisterFile("dht.proto", fileDescriptor_616a434b24c97ff4) }

var fileDescriptor_616a434b24c97ff4 = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x53, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xad, 0xe3, 0x24, 0xad, 0xaf, 0xf3, 0xea, 0x28, 0x8b, 0x51, 0x40, 0xd4, 0xca, 0xca, 0x2c,
	0xe2, 0x48, 0x66, 0xc1, 0x06, 0x21, 0xda, 0xd0, 0x45, 0x15, 0x48, 0xab, 0x21, 0x52, 0x97, 0x28,
	0x63, 0x4f, 0x9d, 0x11, 0x21, 0x63, 0x8d, 0xc7, 0x45, 0xfe, 0x17, 0x7e, 0x85, 0x3d, 0xdf, 0xc0,
	0xa2, 0x3f, 0xc0, 0x4f, 0x20, 0x8f, 0xed, 0xc6, 0x89, 0x10, 0x2c, 0xbb, 0x3b, 0xe7, 0xce, 0x39,
	0x3e, 0xd7, 0x77, 0xee, 0x80, 0x15, 0xae, 0x95, 0x17, 0x4b, 0xa1, 0x04, 0x6a, 0x6b, 0x48, 0x47,
	0xaf, 0x23, 0xae, 0xd6, 0x29, 0xf5, 0x02, 0xf1, 0x75, 0xba, 0xe1, 0x34, 0xf6, 0xe3, 0x69, 0x24,
	0x26, 0x25, 0x0a, 0x84, 0x64, 0xd3, 0x40, 0x66, 0xb1, 0x12, 0xd3, 0x98, 0x96, 0xa8, 0xf8, 0xc0,
	0xc8, 0xff, 0x87, 0x71, 0x22, 0x59, 0x20, 0x64, 0x98, 0x7b, 0x0a, 0x54, 0x7a, 0x26, 0x35, 0x4f,
	0x24, 0x22, 0x31, 0xd5, 0x65, 0x9a, 0xde, 0x69, 0xa6, 0x89, 0x46, 0x85, 0x7c, 0xfc, 0xa3, 0x0d,
	0xc7, 0x1f, 0x59, 0x92, 0xac, 0x22, 0x86, 0x30, 0x1c, 0xdf, 0xb1, 0x95, 0x4a, 0x25, 0xc3, 0x86,
	0x63, 0xb8, 0x16, 0xa9, 0x28, 0x1a, 0x80, 0xf9, 0x85, 0x65, 0xb8, 0xe1, 0x18, 0x6e, 0x87, 0xe4,
	0x10, 0xbd, 0x84, 0x76, 0x11, 0x8b, 0x4d, 0xc7, 0x70, 0x6d, 0xff, 0xd4, 0xab, 0xba, 0xa0, 0x1e,
	0xd1, 0x88, 0x94, 0x02, 0xf4, 0x0e, 0xba, 0xb1, 0x14, 0xf7, 0x3c, 0x64, 0xf2, 0x86, 0x31, 0x99,
	0x60, 0xcb, 0x31, 0x5d, 0xdb, 0x1f, 0x7a, 0xc5, 0x78, 0xbc, 0x32, 0xde, 0xcb, 0x0f, 0x2f, 0x9a,
	0x3f, 0x1f, 0xce, 0x8e, 0xc8, 0xbe, 0x01, 0xbd, 0x01, 0x3b, 0xd8, 0x88, 0xa4, 0xf2, 0x9f, 0xfc,
	0xd7, 0x5f, 0x97, 0x23, 0x17, 0xfa, 0xc1, 0x26, 0x4d, 0x14, 0x93, 0x1f, 0xd8, 0x3d, 0xdb, 0x90,
	0xd5, 0x37, 0x0c, 0x8e, 0xe1, 0xb6, 0xc8, 0x61, 0x19, 0xcd, 0xa1, 0xbf, 0x17, 0x7c, 0x75, 0x85,
	0x6d, 0x9d, 0xf5, 0xec, 0x6f, 0x59, 0xb7, 0x5c, 0xad, 0xe7, 0x2c, 0x2b, 0x23, 0x0f, 0x9d, 0xa3,
	0xef, 0x06, 0x34, 0x73, 0x8c, 0xc6, 0xd0, 0xe0, 0xa1, 0x9e, 0x68, 0xe7, 0x02, 0xe5, 0xda, 0x5f,
	0x0f, 0x67, 0x40, 0x33, 0xc5, 0x3e, 0x29, 0xc9, 0xb7, 0x11, 0x69, 0xf0, 0x10, 0x0d, 0xa1, 0xb5,
	0x0a, 0x43, 0x99, 0xe0, 0x86, 0x63, 0xba, 0x1d, 0x52, 0x10, 0xf4, 0x16, 0x20, 0x10, 0xdb, 0x2d,
	0x0b, 0x14, 0x17, 0x5b, 0x3d, 0xe8, 0x9e, 0xff, 0xe2, 0xb0, 0x95, 0xd9, 0xa3, 0x62, 0x99, 0xc5,
	0x8c, 0xd4, 0x1c, 0x68, 0x04, 0x27, 0xe5, 0x0d, 0x26, 0xb8, 0xe9, 0x98, 0xae, 0x45, 0x1e, 0xf9,
	0xe8, 0xb7, 0x01, 0x76, 0xed, 0x2f, 0x9e, 0xb0, 0xcb, 0x72, 0xb9, 0x9a, 0xbb, 0xe5, 0x7a, 0x0e,
	0x56, 0xc2, 0xa3, 0x6d, 0xb1, 0x8a, 0x2d, 0x5d, 0xdf, 0x15, 0x90, 0x0f, 0x56, 0x9c, 0xd2, 0x0d,
	0x0f, 0xe6, 0x2c, 0xc3, 0x6d, 0xbd, 0x7d, 0x43, 0xaf, 0x7a, 0x37, 0xd4, 0xbb, 0xa9, 0xce, 0xc8,
	0x4e, 0x36, 0xbe, 0x85, 0xde, 0x7e, 0x07, 0xe8, 0x14, 0xba, 0x8b, 0xeb, 0xe5, 0xe7, 0xd9, 0xf5,
	0x62, 0x71, 0x39, 0x5b, 0x5e, 0xbe, 0x1f, 0x1c, 0xa1, 0x2e, 0x58, 0x3b, 0x6a, 0xa0, 0x3e, 0xd8,
	0xb3, 0xf3, 0x45, 0xa5, 0x18, 0x34, 0x10, 0x82, 0xde, 0xec, 0x7c, 0x51, 0x73, 0x0d, 0x4c, 0xda,
	0xd6, 0xcf, 0xe8, 0xd5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x05, 0xb8, 0x03, 0xa1, 0xf7, 0x03,
	0x00, 0x00,
}
